import {host} from './host.config';
const config = {
  /*-----------------------------------授权类---------------------------------------*/
  signIn:{//登录
    host:host.ims,
    url: 'oauth/login',
    method: 'post'
  },
  signOut:{//退出登录
    host:host.ims,
    url: 'iam/employee/logout',
    method: 'post'
  },
  setPassword:{//设置密码
    host:host.ims,
    url: 'iam/employee/setPwd',
    method: 'post'
  },
  refreshToken:{//更新token
    url: 'oauth/refreshToken',
    method: 'get'
  },
  /*-----------------------------------贷款类---------------------------------------*/
  loanList:{//贷款申请列表
    url: 'lms/financeApply/applyList',
    method: 'get'
  },
  loanDetail:{//贷款详情
    url: 'lms/financeApply/applyDetail',
    method: 'get'
  },
  firstApprove:{//用款一审
    url:'lms/financeApply/firstApprove',
    method: 'post'
  },
  finishContract:{//合同完成
    url:'lms/financeApply/contractFinish',
    method: 'post'
  },
  loanApprove:{//用款申请审批
    url: 'lms/financeApply/approve',
    method: 'post'
  },
  loanReview:{//用款申请二审
    url: 'lms/financeApply/secondApprove',
    method: 'post'
  },
  updateLoanStatus:{//更新贷款单状态
    url:'/Loan/UpdateLoanStatus',
    method:'post'
  },
  loanPay:{//放款
    url:'lms/financeApply/pay',
    method:'post'
  },
  cancelLoan:{
    url:'lms/financeApply/cancelApply',
    method:'post'
  },
  getBankCard:{
    url:'sys/user/getBankCard', //memberId=20171101000001&type=1    type:0收款卡   1还款卡
    method:'get'
  },
  loanProveData:{//121用款证明材料列表
    url:'lms/financeApply/proveDataList',
    method:'post'
  },
  applyPayOnline:{//申请线上放款
    url:'lms/financeApply/applyPayOnline',
    method:'post'
  },
  applyPayOffline:{//申请线下放款
    url:'lms/financeApply/applyPayOffline',
    method:'post'
  },
  loanOffline:{//线下放款审批
    url:'lms/financeApply/auditPayOffline',
    method:'post'
  },
  loanOnline:{//线上放款审批
    url:'lms/financeApply/auditPayOnline',
    method:'post'
  },
  loanFlows:{//借款单关联的电子账户流水
    url:'acct/account/getBorrowFlowList',
    method:'get'
  },
  acceptLoan:{//受理借款单
    url:'lms/financeApply/accepted',
    method:'post'
  },
  /*-----------------------------------展期类---------------------------------------*/
  rolloverList:{//展期申请列表
    url:'lms/rolloverApply/applyList',
    method:'post'
  },
  rollover:{//展期详情
    url:'lms/rolloverApply/applyDetail',
    method:'get'
  },
  approveRollover:{//展期审批
    url:'lms/rolloverApply/approve',
    method:'post'
  },
  addProveData:{//添加展期缴费凭证
    url:'lms/rolloverApply/addProvData',
    method:'post'
  },
  finishRolloverContract:{//完成配置合同
    url:'lms/rolloverApply/contractFinish',
    method:'post'
  },
  /*-----------------------------------还款类---------------------------------------*/
  createRepaymentNotify:{//生成还款通知
    url:'/lms/repaymentNotify/saveRepaymentNotify',
    method:'post'
  },
  acceptRepayment:{//受理还款
    url:'lms/repaymentNotify/acceptRepayment',
    method:'post'
  },
  checkRepayment:{//还款核销
    url:'lms/repaymentNotify/checkRepaymentNotify',
    method:'post'
  },
  repayPlanList:{//还款计划列表
    url:'lms/repaymentPlan/repaymentPlanList',
    method:'post'
  },
  repayPlan:{//还款计划详情
    url:'lms/repaymentPlan/repaymentPlanDetail',
    method:'post'
  },
  repayPlanPreview:{
    url:'lms/repaymentPlan/getRepayPlanByRepayDate',
    method:'post'
  },
  repaymentNotifyList:{//还款通知列表
    url:'lms/repaymentNotify/repaymentNotifyList',
    method:'post'
  },
  repaymentNotify:{//还款通知详情
    url:'lms/repaymentNotify/repaymentNotifyDetail',
    method:'post'
  },
  createRepayPlanPreview:{//还款计划预览
    url:'lms/repaymentPlan/repayPlanPreview',
    method:'post'
  },
  repaymentFlows:{//还款通知单关联的电子账户流水
    url:'/acct/account/getRepayFlowList',
    method:'get'
  },
  /*-----------------------------------产品类---------------------------------------*/
  productList:{//产品列表
    url:'/base/products/getList',
    method:'post'
  },
  product:{//产品详情
    url:'base/products/getById',
    method:'get'
  },
  createProduct:{//添加产品
    url:'base/products/create',
    method:'post'
  },
  updateProduct:{//修改产品
    url:'base/products/update',
    method:'post'
  },
  updateProductStatus:{//更改产品状态
    url:'/Product/UpdateStatus',
    method:'post'
  },
  configProduct:{//产品参数配置
    url:'base/products/config',
    method:'post'
  },
  productConfigList:{//产品配置列表
    url:'base/products/getProductsAttachList',
    method:'get'
  },
  deleteProductConfig:{//删除产品配置
    url:'base/products/deleteConfig',
    method:'post'
  },
  updateProductsStatus:{
    url:'base/products/updateProductsStatus',
    method:'post'
  },
  getProveData:{//产品融资证明附件列表
    url:'base/products/getProveDataList',
    method:'post'
  },
  /*-----------------------------------合同类---------------------------------------*/
  createContract:{//合同添加
    url:'tw/contract/createContract',
    method:'post'
  },
  contractList:{//合同列表
    url:'tw/contract/contractList',
    method:'get'
  },
  signContract:{//合同送签
    url:'/Contract/Sign',
    method:'post'
  },
  deleteContract:{//合同删除
    url:'tw/contract/deleteContract',
    method:'post'
  },
  /*-----------------------------------数据类---------------------------------------*/
  resource:{//资方列表
    url:'/base/resource/getList',
    method:'get'
  },
  createCapital:{//资方添加
    url:'/Capital/Create',
    method:'post'
  },
  deleteCapital:{//资方删除
    url:'/Capital/delete',
    method:'post'
  },
  signatories:{//签章用户
    url:'/tw/contract/userList',
    method:'post'
  },
  accountInfo:{//虚拟账户详情
    url:'acct/account/getAccountInfo',
    method:'get'
  },
  bankAccountFlow:{//虚拟账户low流水
    url:'acct/account/getFlow',
    method:'get'
  },
  contractSignatories:{//合同签章信息
    url:'tw/contract/getSignList',
    method:'get'
  },
  /*-----------------------------------系统类---------------------------------------*/
  systemLogs:{//系统日志
    url:'sys/log/logList',
    method:'post'
  },
  capitalBankCards:{//资方银行卡列表
    url:'base/resource/getBankcardList',
    method:'post'
  },
  checkIsUserSignUp:{//根据会员ID查询是否开户
    url:'sys/user/checkIsExist',
    method:'get'
  },
  /*-----------------------------------账户类---------------------------------------*/
  flow:{//流水详情
    url:'acct/account/getFlowDetails',
    method:'get'
  },
  /*-----------------------------------字典类---------------------------------------*/
  dictionary:{//字典
    url:'base/dictionary/dictionaryList',
    method:'get'
  },
  /*-----------------------------------文件---------------------------------------*/
  uploadFile:{//上传文件
    host:host.file,
    url:'file/upload',
    method:'post'
  },
  downloadFile:{//下载文件
    host:host.file,
    url:'file/download',
    method:'get'
  },
  previewFile:{//预览文件
    host:host.file,
    url:'file/preview',
    method:'get'
  },
  removeFile:{//删除文件
    host:host.file,
    url:'file/delete',
    method:'get'
  },
  fileInfo:{//文件信息
    host:host.file,
    url:'file/getInfo',
    method:'get'
  }
};
{//拼接
  for(let o in config){
    config[o].url=(config[o].host||host.fbps)+config[o].url;
  }
}
export const api=config;
